version: "24.0.6"
services:
#container pour Eureka
  discovery:
    container_name: serviceregistry
    build: C:\Users\LENOVO\Desktop\microservice_angular\EurekaServer
    ports:
      - "8761:8761"
    hostname: serviceregistry
    image: "serviceregistry"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/

#container pour voiture
  voiture:
    container_name: voiture
    build: C:\Users\LENOVO\Desktop\microservice_angular\voiture
    ports:
      - "9095:9095"
    hostname: voiture
    image: "voiture"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    depends_on:
      - discovery

#container pour categorie
  categorie:
    container_name: categorie
    build: C:\Users\LENOVO\Desktop\microservice_angular\categorie
    ports:
      - "9092:9092"
    hostname: categorie
    image: "categorie"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    depends_on:
      - discovery

#container pour moto
  projetmicroservice:
    container_name: projetmicroservice
    build: C:\Users\LENOVO\Desktop\microservice_angular\projetmicroservice
    ports:
      - "9098:9098"
    hostname: projetmicroservice
    image: "projetmicroservice"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    depends_on:
      - discovery

#container pour piece
  pieces:
    container_name: pieces
    build: C:\Users\LENOVO\Desktop\microservice_angular\Pieces
    ports:
      - "9091:9091"
    hostname: pieces
    image: "pieces"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    depends_on:
      - discovery

#container pour produits
  produits:
    container_name: produits
    build: C:\Users\LENOVO\Desktop\microservice_angular\Produits
    ports:
      - "9099:9099"
    hostname: produits
    image: "produits"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    depends_on:
      - 
      
#container pour vetements
  vetements:
    container_name: vetements
    build: C:\Users\LENOVO\Desktop\microservice_angular\vetements
    ports:
      - "9096:9096"
    hostname: vetements
    image: "vetements"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    depends_on:
      - discovery

#container pour API_Gateway_Server
  gateway:
    container_name: gatewayapplication
    build: C:\Users\LENOVO\Desktop\microservice_angular\API_Gateway_Server
    ports:
      - "9097:9097"
    hostname: gatewayapplication
    image: "gatewayapplication"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    depends_on:
      - discovery
      
# Conteneur pour MongoDB
  mongodb:
    container_name: mongodb
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=voiture
